"""Optional end-to-end check: pip install playwright && playwright install chromium."""
import json
import os
import re
import sys
import tempfile
import threading
from contextlib import contextmanager
from http.server import ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote

from playwright.sync_api import expect, sync_playwright

ARTIFACTS = Path(__file__).resolve().parents[1] / ".runtime"
ARTIFACTS.mkdir(exist_ok=True)
sys.path.insert(0, str(ARTIFACTS.parent))
from auth import AuthStore
from server import Monitor, make_handler


@contextmanager
def test_server():
    # Never initialize or create accounts in the installed service while testing.
    with tempfile.TemporaryDirectory(prefix="kong-browser-") as directory:
        files=Path(directory) / 'files'
        files.mkdir()
        (files / 'logs').mkdir()
        (files / 'logs' / 'error.log').write_bytes(b'l' * 131072)
        (files / 'large-data.bin').write_bytes(b'd' * 65536)
        (files / '<img src=x onerror=window.storageXSS=true>.txt').write_bytes(b'x' * 4096)
        (files / 'shortcut').symlink_to('/etc',target_is_directory=True)
        auth = AuthStore(directory)
        monitor = Monitor()
        http = ThreadingHTTPServer(("127.0.0.1", 0), make_handler(monitor, auth))
        monitor.start()
        thread = threading.Thread(target=http.serve_forever, daemon=True)
        thread.start()
        try:
            yield f"http://127.0.0.1:{http.server_port}",str(files)
        finally:
            monitor.stop_event.set()
            http.shutdown()
            http.server_close()
            thread.join()


def main():
    with test_server() as environment, sync_playwright() as playwright:
        BASE,FILES=environment
        executable = os.environ.get("KONG_TEST_BROWSER")
        browser = playwright.chromium.launch(headless=True, executable_path=executable, args=["--no-sandbox"])
        context = browser.new_context(viewport={"width": 1440, "height": 1000}, accept_downloads=True)
        page = context.new_page()
        errors = []
        page.on("pageerror", lambda error: errors.append(str(error)))
        page.goto(BASE, wait_until="networkidle")
        expect(page.locator('#auth-form')).to_have_attribute('data-mode', 'setup')
        page.screenshot(path=str(ARTIFACTS / 'setup-desktop.png'), full_page=True)
        page.locator('#auth-username').fill('browser_owner')
        page.locator('#auth-password').fill('browser-owner-password')
        page.locator('#auth-confirm').fill('browser-owner-password')
        page.locator('#auth-form button[type="submit"]').click()
        expect(page.locator(".metric-card")).to_have_count(4)
        assert not page.evaluate("document.documentElement.scrollWidth > innerWidth")
        page.screenshot(path=str(ARTIFACTS / "dashboard-desktop.png"), full_page=True)

        page.locator('[data-range="900"]').click()
        expect(page.locator('[data-range="900"]')).to_have_class("active")
        page.locator(".chart-svg").hover(position={"x": 300, "y": 60})
        expect(page.locator(".chart-tooltip")).to_be_visible()
        page.locator("#page-title").hover()
        expect(page.locator(".chart-tooltip")).to_be_hidden()
        page.locator("#notification-button").click()
        expect(page.locator("#notification-popover")).to_be_visible()
        page.locator("#page-title").click()
        expect(page.locator("#notification-popover")).to_be_hidden()

        page.locator('a[data-page="docker"]').click()
        expect(page.locator("#page-title")).to_contain_text("Docker 容器")
        containers = page.locator("#docker-table-body tr[data-container]")
        # This server has a running container; checks adapt when Docker is empty.
        initial_count = containers.count()
        if initial_count:
            name = page.locator("#docker-table-body .container-name strong").first.inner_text()
            page.locator("#docker-search").fill("a-container-that-does-not-exist")
            expect(containers).to_have_count(0)
            expect(page.locator("#docker-table-body")).to_contain_text("没有匹配的容器")
            page.locator("#docker-search").fill(name)
            expect(containers).to_have_count(1)
            page.wait_for_timeout(2200)
            expect(page.locator("#docker-search")).to_have_value(name)
            page.locator("#docker-search").fill("")
            page.locator('[data-filter="stopped"]').click()
            expect(page.locator('[data-filter="stopped"]')).to_have_class("active")
            page.locator('[data-filter="all"]').click()
            containers.first.click()
            expect(page.locator("#detail-dialog")).to_be_visible()
            expect(page.locator("#detail-content")).to_contain_text(name)
            expect(page.locator("#detail-content")).to_contain_text("端口映射")
            page.locator("#detail-close").click()
            expect(page.locator("#detail-dialog")).to_be_hidden()

        page.locator('a[data-page="overview"]').click()
        page.locator('[data-resource="cpu"]').click()
        expect(page.locator('.metric-card')).to_have_count(0)
        expect(page.locator(".chart-panel")).to_have_count(1)
        expect(page.locator(".core-item").first).to_be_visible()
        expect(page.locator('#resource-processes tr').first).to_be_visible()
        page.locator('.resource-tabs a[href="#resources/memory"]').click()
        expect(page.locator('#memory-info .info-tile')).to_have_count(6)
        page.locator('.resource-tabs a[href="#resources/network"]').click()
        expect(page.locator("#network-interfaces tr").first).to_be_visible()
        assert not page.evaluate("document.documentElement.scrollWidth > innerWidth")
        page.locator('[data-range="3600"]').first.click()
        for button in page.locator('[data-range="3600"]').all():
            expect(button).to_have_class("active")

        page.goto(BASE+'/#resources/disk?path='+quote(FILES,safe=''),wait_until='networkidle')
        expect(page.locator('#storage-result')).to_be_visible(timeout=10000)
        expect(page.locator('#storage-table-body')).to_contain_text('large-data.bin')
        expect(page.locator('#storage-table-body')).to_contain_text('<img src=x onerror=window.storageXSS=true>.txt')
        assert page.evaluate('window.storageXSS !== true')
        assert not page.evaluate('document.documentElement.scrollWidth > innerWidth')
        page.screenshot(path=str(ARTIFACTS / 'storage-desktop.png'),full_page=True)
        page.locator('.storage-entry').filter(has_text='目录 · 点击进入').filter(has_text='logs').click()
        expect(page.locator('#storage-path')).to_have_value(FILES+'/logs')
        expect(page.locator('#storage-result')).to_be_visible(timeout=10000)
        expect(page.locator('#storage-table-body')).to_contain_text('error.log')
        page.locator('.storage-entry').filter(has_text='error.log').click()
        expect(page.locator('#detail-dialog')).to_be_visible()
        expect(page.locator('#detail-content')).to_contain_text('逻辑大小')
        page.locator('#detail-close').click()
        page.locator('#storage-breadcrumb').get_by_role('button',name='files',exact=True).click()
        expect(page.locator('#storage-result')).to_be_visible(timeout=10000)
        page.locator('[data-storage-table="files"]').click()
        expect(page.locator('#storage-table-body')).to_contain_text(FILES+'/logs/error.log')
        page.locator('#storage-filter').fill('does-not-match-any-file')
        expect(page.locator('#storage-table-body')).to_contain_text('没有匹配的文件')
        page.locator('#storage-filter').fill('')
        with page.expect_download() as storage_download:
            page.locator('#storage-export').click()
        storage_report=json.loads(Path(storage_download.value.path()).read_text())
        assert storage_report['analysis']['path']==FILES
        assert storage_report['analysis']['status']=='complete'
        (Path(FILES)/'late-file.bin').write_bytes(b'n'*102400)
        page.locator('#storage-rescan').click()
        expect(page.locator('#storage-result')).to_be_visible(timeout=10000)
        expect(page.locator('#storage-table-body')).to_contain_text('late-file.bin')
        page.locator('#storage-path').fill('/does-not-exist-kong-browser-test')
        page.locator('#storage-scan-button').click()
        expect(page.locator('#storage-error')).to_contain_text('目录不存在')

        page.locator('a[data-page="ports"]').click()
        expect(page.locator('#page-title')).to_contain_text('端口管理')
        server_port=BASE.rsplit(':',1)[1]
        page.locator('#port-search').fill(server_port)
        expect(page.locator('#port-table-body')).to_contain_text(server_port,timeout=10000)
        expect(page.locator('#port-table-body')).to_contain_text('仅本机')
        page.locator('[data-port-detail]').first.click()
        expect(page.locator('#detail-dialog')).to_be_visible()
        expect(page.locator('#detail-content')).to_contain_text('关联进程')
        expect(page.locator('#detail-content')).to_contain_text('可执行文件')
        page.locator('#detail-close').click()
        page.locator('[data-port-sort]').click()
        expect(page.locator('#port-sort-indicator')).to_have_text('↓')
        page.locator('[data-port-sort]').click()
        expect(page.locator('#port-sort-indicator')).to_have_text('↑')
        page.locator('#port-search').fill('a-port-that-does-not-exist')
        expect(page.locator('#port-table-body')).to_contain_text('没有匹配的端口')
        page.locator('#port-search').fill('')
        page.locator('[data-port-filter="udp"]').click()
        assert page.locator('#port-table-body .port-protocol.tcp').count()==0
        page.locator('[data-port-filter="tcp"]').click()
        assert page.locator('#port-table-body .port-protocol.udp').count()==0
        page.locator('[data-port-filter="all"]').click()
        page.locator('#port-scope').select_option('local')
        assert page.locator('#port-table-body .port-scope.all').count()==0
        page.locator('#port-scope').select_option('any')
        assert not page.evaluate('document.documentElement.scrollWidth > innerWidth')
        page.screenshot(path=str(ARTIFACTS/'ports-desktop.png'),full_page=True)
        # Verify service/container metadata is escaped in both inventory and global search.
        page.evaluate("""() => {
          preferences.autoRefresh=false; clearTimeout(state.timer);
          const name='<img src=x onerror=window.portXSS=true>';
          state.data.ports.items.push({id:'tcp|127.0.0.1|65432',protocol:'tcp',address:'127.0.0.1',port:65432,
            family:'IPv4',scope:'local',status:'published',source:'docker',processes:[],
            containers:[{id:'test-container',name,image:'test:image',target_port:80,protocol:'tcp'}]});
          updatePorts();
        }""")
        page.locator('[data-port-filter="docker"]').click()
        page.locator('#port-search').fill('65432')
        expect(page.locator('#port-table-body')).to_contain_text('<img src=x')
        assert page.locator('#port-table-body img').count()==0
        page.locator('[data-port-detail]').first.click()
        expect(page.locator('#detail-content')).to_contain_text('Docker 映射')
        expect(page.locator('#detail-content')).to_contain_text('65432 → 80/tcp')
        assert page.locator('#detail-content img').count()==0
        page.locator('#detail-close').click()
        page.keyboard.press('Control+k')
        page.locator('#global-search').fill('65432')
        expect(page.locator('[data-result-type="port"]')).to_contain_text('<img src=x')
        assert page.locator('#search-results img').count()==0
        assert not page.evaluate('Boolean(window.portXSS)')
        page.locator('#search-close').click()
        page.locator('#port-search').fill('')
        page.locator('[data-port-filter="all"]').click()
        page.evaluate('preferences.autoRefresh=true; fetchData().then(scheduleRefresh)')
        page.goto(BASE+'/#processes',wait_until='networkidle')
        expect(page.locator('#page-title')).to_contain_text('端口管理')
        page.keyboard.press('Control+k')
        page.locator('#global-search').fill(server_port)
        expect(page.locator('[data-result-type="port"]').first).to_be_visible()
        page.locator('[data-result-type="port"]').first.click()
        expect(page.locator('#detail-dialog')).to_be_visible()
        page.locator('#detail-close').click()

        page.keyboard.press("Control+k")
        expect(page.locator("#search-dialog")).to_be_visible()
        page.locator("#global-search").fill("设置")
        page.locator('[data-result-type="page"][data-result-id="settings"]').click()
        expect(page.locator("#page-title")).to_contain_text("偏好设置")
        page.locator('[data-theme="dark"]').click()
        expect(page.locator("body")).to_have_class(re.compile(r"\bdark\b"))
        page.locator("#refresh-interval").select_option("5")
        page.locator("#auto-refresh-toggle").click()
        expect(page.locator("#connection-status")).to_contain_text("自动刷新已暂停")
        page.locator('[data-threshold="memoryThreshold"]').fill("1")
        page.locator('[data-threshold="memoryThreshold"]').press("Tab")
        expect(page.locator("#notification-dot")).to_be_visible()
        page.locator("#notification-button").click()
        expect(page.locator("#notification-popover")).to_contain_text("内存使用率")
        page.locator("#page-title").click()
        page.reload(wait_until="networkidle")
        expect(page.locator("body")).to_have_class(re.compile(r"\bdark\b"))
        expect(page.locator("#refresh-interval")).to_have_value("5")
        expect(page.locator("#auto-refresh-toggle")).to_have_attribute("aria-checked", "false")
        page.locator('[data-threshold="memoryThreshold"]').fill("85")
        page.locator('[data-threshold="memoryThreshold"]').press("Tab")
        page.locator("#auto-refresh-toggle").click()
        page.locator("#refresh-interval").select_option("2")
        page.locator('[data-theme="light"]').click()
        with page.expect_download() as download_event:
            page.locator("#export-button").click()
        report = json.loads(Path(download_event.value.path()).read_text())
        assert report["project"] == "kong" and report["memory"]["total"] > 0
        assert "docker" in report and len(report["history"]) > 0

        page.route("**/api/metrics?*", lambda route: route.abort())
        page.locator('[data-refresh]').click()
        expect(page.locator("#connection-error")).to_be_visible()
        expect(page.locator("#connection-status")).to_contain_text("连接中断")
        page.unroute("**/api/metrics?*")
        page.locator('[data-refresh]').click()
        expect(page.locator("#connection-error")).to_be_hidden()

        mobile = browser.new_page(viewport={"width": 390, "height": 844})
        mobile.on("pageerror", lambda error: errors.append(str(error)))
        mobile.goto(BASE, wait_until='networkidle')
        expect(mobile.locator('#auth-form')).to_have_attribute('data-mode', 'login')
        mobile.screenshot(path=str(ARTIFACTS / 'login-mobile.png'), full_page=True)
        mobile.context.add_cookies(context.cookies())
        mobile.goto(BASE, wait_until="networkidle")
        expect(mobile.locator(".metric-card")).to_have_count(4)
        assert not mobile.evaluate("document.documentElement.scrollWidth > innerWidth")
        mobile.screenshot(path=str(ARTIFACTS / "dashboard-mobile.png"), full_page=True)
        mobile.locator("#menu-button").click()
        expect(mobile.locator("#sidebar")).to_have_class("sidebar open")
        mobile.locator('a[data-page="docker"]').click()
        expect(mobile.locator("#sidebar")).to_have_class("sidebar")
        expect(mobile.locator("#page-title")).to_contain_text("Docker 容器")
        assert not mobile.evaluate("document.documentElement.scrollWidth > innerWidth")
        mobile.locator("#menu-button").click()
        mobile.locator('a[data-page="resources"]').click()
        expect(mobile.locator(".chart-panel")).to_have_count(1)
        assert not mobile.evaluate("document.documentElement.scrollWidth > innerWidth")
        mobile.goto(BASE+'/#resources/disk?path='+quote(FILES,safe=''),wait_until='networkidle')
        expect(mobile.locator('#storage-result')).to_be_visible(timeout=10000)
        assert not mobile.evaluate('document.documentElement.scrollWidth > innerWidth')
        mobile.screenshot(path=str(ARTIFACTS / 'storage-mobile.png'),full_page=True)
        mobile.goto(BASE+'/#ports',wait_until='networkidle')
        expect(mobile.locator('#port-table-body tr').first).to_be_visible()
        assert not mobile.evaluate('document.documentElement.scrollWidth > innerWidth')
        mobile.screenshot(path=str(ARTIFACTS/'ports-mobile.png'),full_page=True)
        mobile.locator('[data-port-detail]').first.click()
        expect(mobile.locator('#detail-dialog')).to_be_visible()
        assert not mobile.evaluate('document.documentElement.scrollWidth > innerWidth')
        mobile.close()
        legacy = browser.new_page(viewport={"width": 390, "height": 844})
        legacy.on("pageerror", lambda error: errors.append(str(error)))
        legacy.add_init_script("AbortSignal.timeout = undefined;")
        legacy.context.add_cookies(context.cookies())
        legacy.goto(BASE, wait_until="networkidle")
        expect(legacy.locator(".metric-card")).to_have_count(4)
        expect(legacy.locator("#connection-error")).to_be_hidden()
        expect(legacy.locator("#connection-status")).to_contain_text("实时监控中")
        legacy.close()
        check_accounts(browser, page, BASE, errors)
        assert not errors, errors
        browser.close()
        print("Browser checks passed: clickable resource cards, resource tabs without duplicate cards, disk directory drill-down, files/search/export/refresh/error/XSS, port inventory/filtering/details/search, monitoring, mobile, legacy browsers, authentication and account management. No JavaScript errors.")


def check_accounts(browser, admin, base, errors):
    admin.locator('a[data-page="settings"]').click()
    admin.locator('[data-settings-tab="users"]').click()
    expect(admin.locator('#users-count')).to_have_text('1 人')
    admin.locator('[data-user-create]').click()
    admin.locator('#new-user-username').fill('created_reader')
    admin.locator('#user-password').fill('created-reader-password')
    admin.locator('#user-password-confirm').fill('created-reader-password')
    admin.locator('#user-form button[type="submit"]').click()
    expect(admin.locator('#users-count')).to_have_text('2 人')
    row = admin.locator('#user-table-body tr').filter(has_text='created_reader')
    row.locator('[data-user-edit]').click()
    admin.locator('#user-role').select_option('admin')
    admin.locator('#user-form button[type="submit"]').click()
    expect(row.locator('.role-badge')).to_have_text('管理员')

    member = browser.new_page(viewport={'width':390, 'height':844})
    member.on('pageerror', lambda error: errors.append(str(error)))
    member.goto(base, wait_until='networkidle')
    member.locator('[data-auth-mode="register"]').click()
    member.locator('#auth-username').fill('registered_reader')
    member.locator('#auth-password').fill('registered-reader-password')
    member.locator('#auth-confirm').fill('registered-reader-password')
    member.locator('#auth-form button[type="submit"]').click()
    expect(member.locator('.form-message.info')).to_contain_text('注册申请已提交')
    member.locator('#auth-username').fill('registered_reader')
    member.locator('#auth-password').fill('registered-reader-password')
    member.locator('#auth-form button[type="submit"]').click()
    expect(member.locator('#auth-error')).to_contain_text('等待管理员审核')

    # User management refreshes on entering settings.
    admin.locator('a[data-page="overview"]').click()
    admin.locator('a[data-page="settings"]').click()
    admin.locator('[data-settings-tab="users"]').click()
    pending = admin.locator('#user-table-body tr').filter(has_text='registered_reader')
    expect(pending.locator('.status-badge')).to_have_text('待审核')
    pending.locator('[data-user-approve]').click()
    expect(pending.locator('.status-badge')).to_have_text('正常')
    member.locator('#auth-form button[type="submit"]').click()
    expect(member.locator('.metric-card')).to_have_count(4)
    member.locator('#menu-button').click()
    member.locator('a[data-page="settings"]').click()
    expect(member.locator('[data-settings-tab="users"]')).to_have_count(0)
    assert member.evaluate("fetch('/api/admin/users').then(response => response.status)") == 403

    pending.locator('[data-user-edit]').click()
    admin.locator('#user-status').select_option('disabled')
    admin.locator('#user-form button[type="submit"]').click()
    expect(pending.locator('.status-badge')).to_have_text('已停用')
    expect(member.locator('#auth-form')).to_be_visible(timeout=8000)
    pending.locator('[data-user-edit]').click()
    admin.locator('#user-status').select_option('active')
    admin.locator('#user-password').fill('reset-reader-password')
    admin.locator('#user-password-confirm').fill('reset-reader-password')
    admin.locator('#user-form button[type="submit"]').click()
    expect(pending.locator('.status-badge')).to_have_text('正常')
    member.locator('#auth-username').fill('registered_reader')
    member.locator('#auth-password').fill('registered-reader-password')
    member.locator('#auth-form button[type="submit"]').click()
    expect(member.locator('#auth-error')).to_contain_text('账号或密码错误')
    member.locator('#auth-password').fill('reset-reader-password')
    member.locator('#auth-form button[type="submit"]').click()
    expect(member.locator('body')).to_have_class('authenticated')
    expect(member.locator('#profile-username')).to_have_text('registered_reader')

    admin.screenshot(path=str(ARTIFACTS / 'users-desktop.png'), full_page=True)
    pending.locator('[data-user-delete]').click()
    admin.locator('#delete-user-confirm').click()
    expect(admin.locator('#users-count')).to_have_text('2 人')
    expect(member.locator('#auth-form')).to_be_visible(timeout=8000)
    admin.locator('#registration-toggle').click()
    expect(admin.locator('#registration-toggle')).to_have_attribute('aria-checked', 'false')
    member.goto(base, wait_until='networkidle')
    expect(member.locator('[data-auth-mode="register"]')).to_have_count(0)
    member.close()

    admin.locator('[data-settings-tab="account"]').click()
    admin.locator('#current-password').fill('browser-owner-password')
    admin.locator('#new-password').fill('changed-owner-password')
    admin.locator('#confirm-new-password').fill('changed-owner-password')
    admin.locator('#password-change-form button[type="submit"]').click()
    expect(admin.locator('#toast')).to_contain_text('密码已修改')
    admin.locator('[data-account-logout]').click()
    expect(admin.locator('#auth-form')).to_be_visible()
    admin.locator('#auth-username').fill('browser_owner')
    admin.locator('#auth-password').fill('browser-owner-password')
    admin.locator('#auth-form button[type="submit"]').click()
    expect(admin.locator('#auth-error')).to_contain_text('账号或密码错误')
    admin.locator('#auth-password').fill('changed-owner-password')
    admin.locator('#auth-form button[type="submit"]').click()
    expect(admin.locator('body')).to_have_class('authenticated')
    admin.reload(wait_until='networkidle')
    expect(admin.locator('#profile-username')).to_have_text('browser_owner')


if __name__ == "__main__":
    main()
